services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: quicksilver-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: quicksilver-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  pipeline:
    build: .
    container_name: quicksilver-pipeline
    env_file:
      - .env
    environment:
      KAFKA_BROKER: kafka:29092
      DBT_PROJECT_DIR: /app/dbt
      DBT_PROFILES_DIR: /app/dbt
      DEFAULT_TICKERS: ""
    depends_on:
      - kafka
    profiles:
      - pipeline
    command: ["python", "pipelines/ingest_raw_headlines.py"]

  sentiment-worker:
    build: .
    container_name: quicksilver-sentiment-worker
    env_file:
      - .env
    environment:
      KAFKA_BROKER: kafka:29092
      SENTIMENT_MAX_MESSAGES: 1000
    depends_on:
      - kafka
    profiles:
      - pipeline
    command: ["python", "pipelines/ingest_score_headlines.py"]

  streamlit:
    build: .
    container_name: quicksilver-streamlit
    env_file:
      - .env
    environment:
      KAFKA_BROKER: kafka:29092
    depends_on:
      - kafka
    ports:
      - "8501:8501"
    profiles:
      - dashboard
    command:
      - streamlit
      - run
      - dashboard/app.py
      - --server.address=0.0.0.0
      - --server.port=8501

  airflow:
    build: .
    container_name: quicksilver-airflow
    env_file:
      - .env
    environment:
      AIRFLOW_HOME: /app/.airflow
      AIRFLOW__CORE__DAGS_FOLDER: /app/orchestration
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      KAFKA_BROKER: kafka:29092
      DBT_PROJECT_DIR: /app/dbt
      DBT_PROFILES_DIR: /app/dbt
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    profiles:
      - airflow
    command: ["airflow", "standalone"]
