"""add ticker and published_at to sentiment

Revision ID: 81ddfdebd2a9
Revises: 
Create Date: 2025-11-29 18:10:59.041988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ddfdebd2a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('window', sa.String(), nullable=False),
    sa.Column('threshold', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('fired_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'kind', 'window', 'fired_at')
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('window', sa.String(), nullable=False),
    sa.Column('ts_utc', sa.String(), nullable=False),
    sa.Column('sent_mean', sa.Float(), nullable=True),
    sa.Column('sent_z', sa.Float(), nullable=True),
    sa.Column('vol_z', sa.Float(), nullable=True),
    sa.Column('headlines_n', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'window', 'ts_utc')
    )
    op.create_table('headlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at_utc', sa.String(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index('idx_headlines_ticker_time', 'headlines', ['ticker', 'published_at_utc'], unique=False)
    op.create_table('sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('published_at_utc', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('score_pos', sa.Float(), nullable=False),
    sa.Column('score_neu', sa.Float(), nullable=False),
    sa.Column('score_neg', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('inference_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['headline_id'], ['headlines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('headline_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiment')
    op.drop_index('idx_headlines_ticker_time', table_name='headlines')
    op.drop_table('headlines')
    op.drop_table('features')
    op.drop_table('alerts')
    # ### end Alembic commands ###
