"""
Public news feed configuration for the local Quicksilver pipeline.

The political topic map intentionally links policy areas to industries and
watchlist tickers. The pipeline stores each matched policy headline against
the affected tickers so the insight engine can treat political catalysts as
market-moving inputs instead of generic news.
"""

from __future__ import annotations

PUBLIC_FINANCIAL_FEEDS: tuple[dict[str, str], ...] = (
    {
        "name": "Yahoo Finance Top Stories",
        "url": "https://finance.yahoo.com/rss/topstories",
    },
    {
        "name": "CNBC Top News",
        "url": "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    },
    {
        "name": "CNBC Business",
        "url": "https://www.cnbc.com/id/10001147/device/rss/rss.html",
    },
    {
        "name": "MarketWatch Top Stories",
        "url": "https://feeds.content.dowjones.io/public/rss/mw_topstories",
    },
    {
        "name": "Nasdaq Stocks",
        "url": "https://www.nasdaq.com/feed/rssoutbound?category=Stocks",
    },
    {
        "name": "SEC Press Releases",
        "url": "https://www.sec.gov/news/pressreleases.rss",
    },
)

PUBLIC_POLICY_FEEDS: tuple[dict[str, str], ...] = (
    {
        "name": "Federal Reserve Press Releases",
        "url": "https://www.federalreserve.gov/feeds/press_all.xml",
    },
    {
        "name": "Federal Reserve Banking Regulation",
        "url": "https://www.federalreserve.gov/feeds/press_bcreg.xml",
    },
    {
        "name": "Federal Reserve Monetary Policy",
        "url": "https://www.federalreserve.gov/feeds/press_monetary.xml",
    },
    {
        "name": "SEC Press Releases",
        "url": "https://www.sec.gov/news/pressreleases.rss",
    },
    {
        "name": "U.S. Treasury Press Releases",
        "url": "https://home.treasury.gov/news/press-releases/rss",
    },
    {
        "name": "FTC Press Releases",
        "url": "https://www.ftc.gov/feeds/press-release.xml",
    },
    {
        "name": "FTC Competition Press Releases",
        "url": "https://www.ftc.gov/feeds/press-release-competition.xml",
    },
    {
        "name": "FDA Press Releases",
        "url": "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/press-releases/rss.xml",
    },
    {
        "name": "CFTC General Press Releases",
        "url": "https://www.cftc.gov/RSS/RSSGP/rssgp.xml",
    },
)

TICKER_COMPANY_NAMES: dict[str, str] = {
    "NVDA": "Nvidia",
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "AMZN": "Amazon",
    "GOOGL": "Alphabet",
    "GOOG": "Alphabet",
    "META": "Meta",
    "TSLA": "Tesla",
    "BRK.B": "Berkshire Hathaway",
    "JPM": "JPMorgan",
    "LLY": "Eli Lilly",
    "V": "Visa",
    "NFLX": "Netflix",
    "MA": "Mastercard",
    "XOM": "Exxon Mobil",
    "WMT": "Walmart",
    "COST": "Costco",
    "JNJ": "Johnson & Johnson",
    "PG": "Procter Gamble",
    "HD": "Home Depot",
    "ABBV": "AbbVie",
    "BAC": "Bank of America",
    "ORCL": "Oracle",
    "KO": "Coca-Cola",
    "PM": "Philip Morris",
    "GE": "GE",
    "CSCO": "Cisco",
    "CRM": "Salesforce",
    "CVX": "Chevron",
    "WFC": "Wells Fargo",
    "ABT": "Abbott",
    "IBM": "IBM",
    "MCD": "McDonald's",
    "AMD": "AMD",
    "LIN": "Linde",
    "MRK": "Merck",
    "TMO": "Thermo Fisher",
    "DIS": "Disney",
    "PEP": "PepsiCo",
    "NOW": "ServiceNow",
    "ACN": "Accenture",
    "ISRG": "Intuitive Surgical",
    "QCOM": "Qualcomm",
    "INTU": "Intuit",
    "UBER": "Uber",
    "VZ": "Verizon",
    "TXN": "Texas Instruments",
    "CAT": "Caterpillar",
    "AMGN": "Amgen",
    "AVGO": "Broadcom",
    "ADBE": "Adobe",
    "AMAT": "Applied Materials",
    "ANET": "Arista Networks",
    "AXP": "American Express",
    "BA": "Boeing",
    "BKNG": "Booking Holdings",
    "BLK": "BlackRock",
    "C": "Citigroup",
    "CMCSA": "Comcast",
    "COP": "ConocoPhillips",
    "DHR": "Danaher",
    "ELV": "Elevance Health",
    "ETN": "Eaton",
    "FI": "Fiserv",
    "GS": "Goldman Sachs",
    "HON": "Honeywell",
    "LOW": "Lowe's",
    "LRCX": "Lam Research",
    "MS": "Morgan Stanley",
    "MU": "Micron",
    "NEE": "NextEra Energy",
    "NKE": "Nike",
    "PANW": "Palo Alto Networks",
    "PFE": "Pfizer",
    "PLD": "Prologis",
    "RTX": "RTX",
    "SBUX": "Starbucks",
    "SCHW": "Charles Schwab",
    "SPGI": "S&P Global",
    "T": "AT&T",
    "UNH": "UnitedHealth",
    "UNP": "Union Pacific",
    "UPS": "UPS",
    "VRTX": "Vertex Pharmaceuticals",
    "SHOP": "Shopify",
    "RY": "Royal Bank of Canada",
    "TD": "Toronto-Dominion Bank",
    "BMO": "Bank of Montreal",
    "BNS": "Bank of Nova Scotia",
    "CM": "Canadian Imperial Bank of Commerce",
    "CNQ": "Canadian Natural Resources",
    "ENB": "Enbridge",
    "TRP": "TC Energy",
    "SU": "Suncor Energy",
    "BCE": "BCE",
    "CP": "Canadian Pacific Kansas City",
    "CNR": "Canadian National Railway",
    "ATD": "Alimentation Couche-Tard",
    "IFC": "Intact Financial",
    "MFC": "Manulife",
}

TICKER_SECTORS: dict[str, str] = {
    "NVDA": "semiconductors",
    "AMD": "semiconductors",
    "AVGO": "semiconductors",
    "QCOM": "semiconductors",
    "TXN": "semiconductors",
    "AMAT": "semiconductors",
    "LRCX": "semiconductors",
    "MU": "semiconductors",
    "AAPL": "big_tech",
    "MSFT": "big_tech",
    "GOOGL": "big_tech",
    "GOOG": "big_tech",
    "META": "big_tech",
    "AMZN": "big_tech",
    "ORCL": "big_tech",
    "CRM": "big_tech",
    "NOW": "big_tech",
    "ADBE": "big_tech",
    "INTU": "big_tech",
    "IBM": "big_tech",
    "PANW": "cybersecurity",
    "ANET": "networking",
    "CSCO": "networking",
    "JPM": "banks_payments",
    "BAC": "banks_payments",
    "WFC": "banks_payments",
    "C": "banks_payments",
    "GS": "banks_payments",
    "MS": "banks_payments",
    "SCHW": "banks_payments",
    "BLK": "asset_management",
    "AXP": "banks_payments",
    "V": "banks_payments",
    "MA": "banks_payments",
    "FI": "banks_payments",
    "SPGI": "market_data",
    "RY": "canadian_banks",
    "TD": "canadian_banks",
    "BMO": "canadian_banks",
    "BNS": "canadian_banks",
    "CM": "canadian_banks",
    "XOM": "energy",
    "CVX": "energy",
    "COP": "energy",
    "CNQ": "energy",
    "ENB": "pipelines",
    "TRP": "pipelines",
    "SU": "energy",
    "LLY": "healthcare_pharma",
    "JNJ": "healthcare_pharma",
    "ABBV": "healthcare_pharma",
    "MRK": "healthcare_pharma",
    "ABT": "healthcare_pharma",
    "AMGN": "healthcare_pharma",
    "TMO": "healthcare_tools",
    "DHR": "healthcare_tools",
    "ISRG": "medical_devices",
    "UNH": "managed_care",
    "ELV": "managed_care",
    "PFE": "healthcare_pharma",
    "VRTX": "healthcare_pharma",
    "WMT": "consumer_retail",
    "COST": "consumer_retail",
    "HD": "consumer_retail",
    "LOW": "consumer_retail",
    "KO": "consumer_staples",
    "PEP": "consumer_staples",
    "PG": "consumer_staples",
    "MCD": "restaurants",
    "SBUX": "restaurants",
    "PM": "consumer_staples",
    "NKE": "apparel",
    "ATD": "consumer_retail",
    "UBER": "transport_industrials",
    "CAT": "transport_industrials",
    "GE": "aerospace_industrials",
    "BA": "aerospace_industrials",
    "RTX": "aerospace_defense",
    "HON": "aerospace_industrials",
    "ETN": "electrification",
    "LIN": "chemicals",
    "UNP": "rails_logistics",
    "CP": "rails_logistics",
    "CNR": "rails_logistics",
    "UPS": "logistics",
    "NFLX": "media_entertainment",
    "DIS": "media_entertainment",
    "CMCSA": "media_entertainment",
    "VZ": "telecom",
    "T": "telecom",
    "BCE": "telecom",
    "TSLA": "electric_vehicles",
    "NEE": "utilities_renewables",
    "PLD": "real_estate_logistics",
    "BKNG": "travel",
    "SHOP": "ecommerce",
    "ACN": "consulting_it_services",
    "BRK.B": "diversified_financials",
    "IFC": "insurance",
    "MFC": "insurance",
}

INDUSTRY_TICKERS: dict[str, tuple[str, ...]] = {
    "semiconductors": ("NVDA", "AMD", "AVGO", "QCOM", "TXN", "AMAT", "LRCX", "MU"),
    "big_tech": (
        "AAPL",
        "MSFT",
        "GOOGL",
        "GOOG",
        "META",
        "AMZN",
        "ORCL",
        "CRM",
        "ADBE",
        "INTU",
        "NOW",
        "IBM",
    ),
    "cybersecurity": ("PANW",),
    "banks_payments": ("JPM", "BAC", "WFC", "C", "GS", "MS", "SCHW", "AXP", "V", "MA", "FI"),
    "canadian_banks": ("RY", "TD", "BMO", "BNS", "CM"),
    "energy": ("XOM", "CVX", "COP", "CNQ", "SU"),
    "pipelines": ("ENB", "TRP"),
    "healthcare_pharma": (
        "LLY",
        "JNJ",
        "ABBV",
        "MRK",
        "ABT",
        "AMGN",
        "TMO",
        "DHR",
        "ISRG",
        "UNH",
        "ELV",
        "PFE",
        "VRTX",
    ),
    "consumer_retail": (
        "WMT",
        "COST",
        "HD",
        "LOW",
        "KO",
        "PEP",
        "PG",
        "MCD",
        "SBUX",
        "PM",
        "NKE",
        "ATD",
    ),
    "transport_industrials": (
        "UBER",
        "CAT",
        "GE",
        "BA",
        "RTX",
        "HON",
        "ETN",
        "LIN",
        "UNP",
        "CP",
        "CNR",
        "UPS",
    ),
    "aerospace_defense": ("BA", "RTX", "HON", "GE"),
    "electrification_grid": ("ETN", "GE", "LIN", "NEE"),
    "media_entertainment": ("NFLX", "DIS", "CMCSA"),
    "telecom": ("VZ", "T", "BCE", "CSCO", "ANET"),
    "electric_vehicles": ("TSLA",),
    "travel": ("BKNG",),
    "real_estate_logistics": ("PLD",),
    "asset_management_insurance": ("BLK", "SPGI", "BRK.B", "IFC", "MFC"),
    "payments_networks": ("V", "MA", "FI", "AXP"),
    "managed_care": ("UNH", "ELV"),
    "ecommerce": ("AMZN", "SHOP"),
}

POLITICAL_INDUSTRY_TOPICS: tuple[dict[str, object], ...] = (
    {
        "topic": "semiconductor_export_controls",
        "industry": "semiconductors",
        "query": '"semiconductor" "export controls" OR "CHIPS Act"',
        "tickers": INDUSTRY_TICKERS["semiconductors"],
        "keywords": ("semiconductor", "chip", "chips act", "export control", "advanced computing"),
    },
    {
        "topic": "big_tech_antitrust_regulation",
        "industry": "big_tech",
        "query": '"antitrust" "big tech" OR "technology regulation"',
        "tickers": INDUSTRY_TICKERS["big_tech"],
        "keywords": (
            "antitrust",
            "big tech",
            "technology regulation",
            "app store",
            "platform",
            "privacy rule",
            "data protection",
        ),
    },
    {
        "topic": "banking_regulation_rates",
        "industry": "banks_payments",
        "query": '"bank regulation" OR "interest rates" "Federal Reserve"',
        "tickers": INDUSTRY_TICKERS["banks_payments"],
        "keywords": ("federal reserve", "interest rate", "bank capital", "stress test", "basel"),
    },
    {
        "topic": "payments_interchange_regulation",
        "industry": "payments_networks",
        "query": '"interchange fees" OR "credit card competition" regulation',
        "tickers": INDUSTRY_TICKERS["payments_networks"],
        "keywords": (
            "interchange",
            "credit card competition",
            "payment network",
            "card fees",
            "debit routing",
        ),
    },
    {
        "topic": "canadian_bank_regulation_rates",
        "industry": "canadian_banks",
        "query": '"Bank of Canada" "interest rates" OR "OSFI" bank regulation',
        "tickers": INDUSTRY_TICKERS["canadian_banks"],
        "keywords": ("bank of canada", "osfi", "capital buffer", "mortgage", "interest rate"),
    },
    {
        "topic": "energy_policy_oil_gas",
        "industry": "energy",
        "query": '"energy policy" "oil and gas" OR "drilling permits"',
        "tickers": INDUSTRY_TICKERS["energy"],
        "keywords": ("oil", "gas", "drilling", "pipeline", "lng", "energy policy", "emissions"),
    },
    {
        "topic": "ai_power_grid_permitting",
        "industry": "electrification_grid",
        "query": '"data center" power demand OR grid permitting OR transmission policy',
        "tickers": INDUSTRY_TICKERS["electrification_grid"],
        "keywords": (
            "data center",
            "grid",
            "transmission",
            "power demand",
            "electricity demand",
            "permitting reform",
        ),
    },
    {
        "topic": "pipeline_permitting_policy",
        "industry": "pipelines",
        "query": '"pipeline permitting" OR "energy infrastructure" policy',
        "tickers": INDUSTRY_TICKERS["pipelines"],
        "keywords": ("pipeline", "permitting", "energy infrastructure", "transmission"),
    },
    {
        "topic": "drug_pricing_healthcare_policy",
        "industry": "healthcare_pharma",
        "query": '"drug pricing" OR "FDA approval" OR "healthcare policy"',
        "tickers": INDUSTRY_TICKERS["healthcare_pharma"],
        "keywords": ("drug pricing", "fda", "medicare", "healthcare policy", "clinical trial"),
    },
    {
        "topic": "managed_care_medicare_policy",
        "industry": "managed_care",
        "query": '"Medicare Advantage" policy OR managed care regulation',
        "tickers": INDUSTRY_TICKERS["managed_care"],
        "keywords": (
            "medicare advantage",
            "managed care",
            "rate notice",
            "cms",
            "health insurer",
        ),
    },
    {
        "topic": "consumer_tariffs_retail_policy",
        "industry": "consumer_retail",
        "query": '"tariffs" "retail" OR "consumer prices" policy',
        "tickers": INDUSTRY_TICKERS["consumer_retail"],
        "keywords": ("tariff", "consumer price", "retail", "minimum wage", "food inflation"),
    },
    {
        "topic": "labor_wage_consumer_policy",
        "industry": "consumer_retail",
        "query": '"minimum wage" OR labor rule retail restaurants',
        "tickers": INDUSTRY_TICKERS["consumer_retail"],
        "keywords": (
            "minimum wage",
            "overtime rule",
            "labor rule",
            "union",
            "worker classification",
        ),
    },
    {
        "topic": "infrastructure_transport_policy",
        "industry": "transport_industrials",
        "query": '"infrastructure bill" OR "transportation policy"',
        "tickers": INDUSTRY_TICKERS["transport_industrials"],
        "keywords": ("infrastructure", "transportation", "rail", "aerospace", "defense", "supply chain"),
    },
    {
        "topic": "defense_procurement_budget",
        "industry": "aerospace_defense",
        "query": '"defense budget" OR "defense procurement" aerospace',
        "tickers": INDUSTRY_TICKERS["aerospace_defense"],
        "keywords": (
            "defense budget",
            "defense procurement",
            "missile",
            "fighter jet",
            "aerospace contract",
        ),
    },
    {
        "topic": "ev_tax_credits_emissions_policy",
        "industry": "electric_vehicles",
        "query": '"EV tax credit" OR "vehicle emissions rules"',
        "tickers": INDUSTRY_TICKERS["electric_vehicles"],
        "keywords": ("ev tax credit", "electric vehicle", "emissions", "battery", "clean vehicle"),
    },
    {
        "topic": "cybersecurity_policy",
        "industry": "cybersecurity",
        "query": '"cybersecurity" regulation OR "critical infrastructure" cyber',
        "tickers": INDUSTRY_TICKERS["cybersecurity"],
        "keywords": ("cybersecurity", "ransomware", "critical infrastructure", "data breach"),
    },
    {
        "topic": "ai_export_controls_cloud",
        "industry": "big_tech",
        "query": '"AI export controls" OR cloud computing restrictions',
        "tickers": INDUSTRY_TICKERS["big_tech"],
        "keywords": (
            "ai export",
            "cloud restriction",
            "advanced ai",
            "compute rule",
            "model weights",
        ),
    },
    {
        "topic": "telecom_spectrum_policy",
        "industry": "telecom",
        "query": '"spectrum auction" OR "telecom regulation" OR broadband policy',
        "tickers": INDUSTRY_TICKERS["telecom"],
        "keywords": ("spectrum", "telecom", "broadband", "net neutrality", "fcc"),
    },
    {
        "topic": "travel_border_policy",
        "industry": "travel",
        "query": '"travel restrictions" OR "visa policy" tourism',
        "tickers": INDUSTRY_TICKERS["travel"],
        "keywords": ("travel", "visa", "tourism", "border", "airline"),
    },
    {
        "topic": "real_estate_rates_logistics",
        "industry": "real_estate_logistics",
        "query": '"commercial real estate" rates OR warehouse demand',
        "tickers": INDUSTRY_TICKERS["real_estate_logistics"],
        "keywords": ("commercial real estate", "warehouse", "industrial property", "rates"),
    },
    {
        "topic": "insurance_climate_capital_rules",
        "industry": "asset_management_insurance",
        "query": '"insurance" climate risk capital rules OR reinsurance regulation',
        "tickers": INDUSTRY_TICKERS["asset_management_insurance"],
        "keywords": (
            "insurance",
            "climate risk",
            "catastrophe",
            "capital rule",
            "reinsurance",
        ),
    },
    {
        "topic": "ecommerce_marketplace_rules",
        "industry": "ecommerce",
        "query": '"online marketplace" regulation OR ecommerce antitrust',
        "tickers": INDUSTRY_TICKERS["ecommerce"],
        "keywords": (
            "online marketplace",
            "ecommerce",
            "seller fees",
            "marketplace rule",
            "digital services",
        ),
    },
)

POLICY_SUPPORTIVE_KEYWORDS: tuple[str, ...] = (
    "approval",
    "approved",
    "incentive",
    "subsidy",
    "tax credit",
    "permit",
    "permitting reform",
    "funding",
    "grant",
    "contract",
    "relief",
    "deregulation",
    "rate cut",
    "lower rates",
    "investment",
)

POLICY_RESTRICTIVE_KEYWORDS: tuple[str, ...] = (
    "ban",
    "blocked",
    "lawsuit",
    "probe",
    "investigation",
    "fine",
    "tariff",
    "sanction",
    "export control",
    "restriction",
    "cap",
    "price negotiation",
    "higher capital",
    "rate hike",
    "emissions limit",
)


def get_sector_for_ticker(ticker: str) -> str | None:
    return TICKER_SECTORS.get(ticker.upper())


def classify_policy_impact(text: str) -> str:
    normalized = text.casefold()
    supportive_hits = sum(
        1
        for keyword in POLICY_SUPPORTIVE_KEYWORDS
        if keyword.casefold() in normalized
    )
    restrictive_hits = sum(
        1
        for keyword in POLICY_RESTRICTIVE_KEYWORDS
        if keyword.casefold() in normalized
    )
    if supportive_hits > restrictive_hits:
        return "supportive"
    if restrictive_hits > supportive_hits:
        return "restrictive"
    return "mixed_or_unclear"
